name: Check
on:
  pull_request:
    branches:
      - 'master'
      - 'release/*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  check:
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, preset: linuxX64 }
    name: Check on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: -si generateNativeClasses check
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g
      - name: Publish test report to artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: '~/**/test-results/**/*.xml'
