name: Check
on:
  pull_request:
    branches:
      - 'master'
      - 'release/*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  check:
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, preset: linuxX64 }
    name: Check on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - run: sudo apt-get remove google-chrome-stable
      - run: wget https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb
      - run: sudo dpkg -i --force-depends google-chrome-beta_current_amd64.deb
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: -si generateNativeClasses check
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g
