name: Build & publish autotest artifacts
on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish_for_nix:
    name: Publish for nix platforms (macOS, Linux)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon -si publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx4096m

  build_and_publish_for_win:
    name: Publish for Windows platform (Windows platform)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -si generateNativeClasses publishMingwX64ZipPublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
